
ALTER TABLE pcs ADD CONSTRAINT pk_somekey PRIMARY KEY (id);
ALTER TABLE soft ADD CONSTRAINT sof_key PRIMARY KEY (id);
ALTER TABLE rooms ADD CONSTRAINT roo_key PRIMARY KEY (id);
ALTER TABLE employees ADD CONSTRAINT emp_key PRIMARY KEY (id);

ALTER TABLE installs ADD CONSTRAINT fk_inst_pc_id FOREIGN KEY (pc_id) REFERENCES pcs (id);
ALTER TABLE installs ADD CONSTRAINT sof_id FOREIGN KEY (soft_id) REFERENCES soft (id);
ALTER TABLE pcs ADD CONSTRAINT roo_id FOREIGN KEY (room_id) REFERENCES rooms (id);
ALTER TABLE rooms ADD CONSTRAINT em_id FOREIGN KEY (emp_id) REFERENCES employees (id);
